version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    volumes:
      - ./es-data:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    container_name: docker-sysmonsearch-es
    environment:
      #- cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
        - 9200:9200
    expose:
        - 9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.5.1
#    build:
#      context: kibana
#      args:
#        - http_proxy=[proxy_server_URL]
#        - https_proxy=[proxy_server_URL]
    volumes:
      - ../sysmon_search_plugin:/usr/share/kibana/plugins/sysmon_search_plugin
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
      - ./conf.js:/usr/share/kibana/plugins/sysmon_search_plugin/conf.js
      - ./rule_files:/tmp/rule_files
    #  - rule_files:/usr/share/kibana/rule_files
    #  - rule_files:/usr/share/kibana/rule_files
    container_name: docker-sysmonsearch-kibana
    ports:
      - 127.0.0.1:5601:5601
  stixioc-import-server:
    build:
      context: stixioc-import-server
#      args:
#        - http_proxy=[proxy_server_URL]
#        - https_proxy=[proxy_server_URL]
    command: bash -c "cd /root/stixioc-import-server/ && python server.py"
    volumes:
      - ./rule_files:/root/script/rule_files
      - ../winlogbeat.yml:/root/winlogbeat.yml
      - ../script:/root/script
      - ../stixioc-import-server:/root/stixioc-import-server
    container_name: docker-stixioc-import-server
    ports:
      - 56020:56020

